name: LCA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        instance: [1]
#        instance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
#                   11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
#                   21, 22, 23, 24, 25]

    env:
      PY_COLORS: "1"
      CATALOG_USERNAME: ${{ secrets.CATALOG_USERNAME }}
      CATALOG_PASSWORD: ${{ secrets.CATALOG_PASSWORD }}
      LCA_PASSWORD: ${{ secrets.LCA_PASSWORD }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Setup Chrome and ChromeDriver
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -U seleniumbase

    - name: Run test instance ${{ matrix.instance }}
      continue-on-error: true
      run: |
        echo "Running test instance ${{ matrix.instance }}"
        pytest examples/nypl_tests --pspec --headless --reruns=2 --reruns-delay=2 --env=qa -m "test and lca and imperva"
