name: Prod Regression

on:
  workflow_dispatch:

jobs:
  build:
    env:
      PY_COLORS: "1"
      CATALOG_USERNAME: ${{ secrets.CATALOG_USERNAME }}
      CATALOG_PASSWORD: ${{ secrets.CATALOG_PASSWORD }}
      LCA_PASSWORD: ${{ secrets.LCA_PASSWORD }}

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 60
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup Chrome and ChromeDriver
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt
        pip install -U seleniumbase flake8

    - name: Run Flake8 Linter
      continue-on-error: true
      run: flake8 examples/nypl_tests --max-line-length=120 --statistics --count || true

    - name: Run all tests
      continue-on-error: true
      run: |
        pytest examples/nypl_tests --pspec --headless -n=60 --reruns=2 --reruns-delay=2 -m "not test"
