name: QA Regression

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:

    env:
      PY_COLORS: "1"
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        python-version: ["3.10"] 

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup Chrome and ChromeDriver
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade wheel
        pip install -r requirements.txt
    - name: Install SeleniumBase
      run: |
        python setup.py install
    - name: Check the console scripts interface
      run: |
        seleniumbase
        sbase
    - name: Make sure pytest is working
      run: |
        echo "def test_1(): pass" > nothing.py
        pytest nothing.py
    - name: Make sure nosetests is working
      run: |
        echo "def test_2(): pass" > nothing2.py
        nosetests nothing2.py
        
    
   # NYPL tests for the following pages;
    # footer, header, blog, blog all, book lists, campaigns, exhibitions, locations, articles & databases, home, give,
    # schwarzman, research, research_support, SNFL, SNFL teen, billy rose, request visit, posada exhibition, world literature,
    # articles burney, articles homework, blog channels, blog individual, press, press individual

    - name: Run all tests
      run: |
        pytest examples --headless --browser=chrome --rs -v -s -n=6 --reruns=2 --reruns-delay=1 --env=qa
    
    
    # - name: Run pytest test_footer.py
    #   continue-on-error: true
    #   run: |
    #     pytest examples/nypl_tests/test_footer.py --rs --browser=chrome --headless -v -s -n=6 --reruns=2 --env=qa
    
    
    # - name: Run pytest test_header.py
    #   continue-on-error: true
    #   run: |
    #     pytest examples/nypl_tests/test_header.py --rs --browser=chrome --headless -v -s -n=6 --reruns=2 --env=qa
    
    
    # - name: Run pytest test_blog.py
    #   continue-on-error: true
    #   run: |
    #     pytest examples/nypl_tests/test_blog.py --rs --browser=chrome --headless -v -s -n=6 --reruns=2 --env=qa
    
    
    # - name: Run pytest test_blog_all.py
    #   continue-on-error: true
    #   run: |
    #     pytest examples/nypl_tests/test_blog_all.py --rs --browser=chrome --headless -v -s -n=6 --reruns=2 --env=qa
    
    
    # - name: Run pytest test_book_lists.py
    #   continue-on-error: true
    #   run: |
    #     pytest examples/nypl_tests/test_book_lists.py --rs --browser=chrome --headless -v -s -n=6 --reruns=2 --env=qa
    
        
    # - name: Run pytest test_campaigns.py
    #   continue-on-error: true
    #   run: |
    #     pytest examples/nypl_tests/test_campaigns.py --rs --browser=chrome --headless -v -s -n=6 --reruns=2 --env=qa
    
    
    # - name: Run pytest test_exhibitions.py
    #   continue-on-error: true
    #   run: |
    #     pytest examples/nypl_tests/test_exhibitions.py --rs --browser=chrome --headless -v -s -n=6 --reruns=2 --env=qa
        
        
    # - name: Run pytest test_locations.py
    #   continue-on-error: true
    #   run: |
    #     pytest examples/nypl_tests/test_locations.py --rs --browser=chrome --headless -v -s -n=6 --reruns=2 --env=qa
        
        
    # - name: Run pytest test_articles_databases.py
    #   continue-on-error: true
    #   run: |
    #     pytest examples/nypl_tests/test_articles_databases.py --rs --browser=chrome --headless -v -s -n=6 --reruns=2 --env=qa
        

    # - name: Run pytest test_home.py
    #   continue-on-error: true
    #   run: |
    #     pytest examples/nypl_tests/test_home.py --rs --browser=chrome --headless -v -s -n=6 --reruns=2 --env=qa
        

    # - name: Run pytest test_give.py
    #   continue-on-error: true
    #   run: |
    #     pytest examples/nypl_tests/test_give.py --rs --browser=chrome --headless -v -s -n=6 --reruns=2 --env=qa
        

    # - name: Run pytest test_schwarzman.py
    #   continue-on-error: true
    #   run: |
    #     pytest examples/nypl_tests/test_schwarzman.py --rs --browser=chrome --headless -v -s -n=6 --reruns=2 --env=qa
        

    # - name: Run pytest test_research.py
    #   continue-on-error: true
    #   run: |
    #     pytest examples/nypl_tests/test_research.py --rs --browser=chrome --headless -v -s -n=6 --reruns=2 --env=qa
        

    # - name: Run pytest test_research_support.py
    #   continue-on-error: true
    #   run: |
    #     pytest examples/nypl_tests/test_research_support.py --rs --browser=chrome --headless -v -s -n=6 --reruns=2 --env=qa
        

    # - name: Run pytest test_snfl.py
    #   continue-on-error: true
    #   run: |
    #     pytest examples/nypl_tests/test_snfl.py --rs --browser=chrome --headless -v -s -n=6 --reruns=2 --env=qa
        

    # - name: Run pytest test_snfl_teen.py
    #   continue-on-error: true
    #   run: |
    #     pytest examples/nypl_tests/test_snfl_teen.py --rs --browser=chrome --headless -v -s -n=6 --reruns=2 --env=qa
        

    # - name: Run pytest test_billy_rose.py
    #   continue-on-error: true
    #   run: |
    #     pytest examples/nypl_tests/test_billy_rose.py --rs --browser=chrome --headless -v -s -n=6 --reruns=2 --env=qa
        

    # - name: Run pytest test_request_visit.py
    #   continue-on-error: true
    #   run: |
    #     pytest examples/nypl_tests/test_request_visit.py --rs --browser=chrome --headless -v -s -n=6 --reruns=2 --env=qa
        

    # - name: Run pytest test_posada.py
    #   continue-on-error: true
    #   run: |
    #     pytest examples/nypl_tests/test_posada.py --rs --browser=chrome --headless -v -s -n=6 --reruns=2 --env=qa

    # - name: Run pytest test_world_literature.py
    #   continue-on-error: true
    #   run: |
    #     pytest examples/nypl_tests/test_world_literature.py --rs --browser=chrome --headless -v -s -n=6 --reruns=2 --env=qa

    # - name: Run pytest test_articles_burney.py
    #   continue-on-error: true
    #   run: |
    #     pytest examples/nypl_tests/test_articles_burney.py --rs --browser=chrome --headless -v -s -n=6 --reruns=2 --env=qa

    # - name: Run pytest test_articles_homework.py
    #   continue-on-error: true
    #   run: |
    #     pytest examples/nypl_tests/test_articles_homework.py --rs --browser=chrome --headless -v -s -n=6 --reruns=2 --env=qa

    # - name: Run pytest test_blog_channels.py
    #   continue-on-error: true
    #   run: |
    #     pytest examples/nypl_tests/test_blog_channels.py --rs --browser=chrome --headless -v -s -n=6 --reruns=2 --env=qa

    # - name: Run pytest test_blog_individual.py
    #   continue-on-error: true
    #   run: |
    #     pytest examples/nypl_tests/test_blog_individual.py --rs --browser=chrome --headless -v -s -n=6 --reruns=2 --env=qa

    # - name: Run pytest test_press.py
    #   continue-on-error: true
    #   run: |
    #     pytest examples/nypl_tests/test_press.py --rs --browser=chrome --headless -v -s -n=6 --reruns=2 --env=qa

    # - name: Run pytest test_press_individual.py
    #   continue-on-error: true
    #   run: |
    #     pytest examples/nypl_tests/test_press_individual.py --rs --browser=chrome --headless -v -s -n=6 --reruns=2 --env=qa
